

mastodon.test {
    tls /etc/caddy/certs/mastodon.test+3.pem /etc/caddy/certs/mastodon.test+3-key.pem
    reverse_proxy localhost:3000
}

soap.test {
    tls /etc/caddy/certs/mastodon.test+3.pem /etc/caddy/certs/mastodon.test+3-key.pem
    reverse_proxy localhost:55000
}

solid.test {
    tls /etc/caddy/certs/mastodon.test+3.pem /etc/caddy/certs/mastodon.test+3-key.pem
    reverse_proxy bob.localhost:33000
}

*.solid.test {
    tls /etc/caddy/certs/mastodon.test+3.pem /etc/caddy/certs/mastodon.test+3-key.pem
    reverse_proxy alice.localhost:33000
}

