name: Code Quality

on:
  push:
  pull_request:

jobs:
  ci:
    name: Lint, Format, Clutter & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install NPM packages
        run: npm ci

      - name: Check code style
        run: npm run lint -- --max-warnings 0

      - name: Check formatting
        run: npx prettier . --check

      - name: Check clutter
        run: npm run knip

      - name: Check that TypeScript compiles
        run: npx tsc
